### ISSUE TITLE
Not all content downloading?

### ISSUE THREAD

**Issue by root3d1** [DIGITALCRIMINAL/UltimaScraper#1472]
Hi, i don't know if im being stupid but im on the latest version and sometimes particularly on models with loads of content it only downloads a quarter of the content. Have i done something wrong in the config file or am i missing something? Thanks

**Comment by LordAbortion** [comment]
+1, only getting headers

**Comment by root3d1** [comment]
Just tried that and it didn't have any effect :(

**Comment by root3d1** [comment]
It seems to be to do with the connection. After switching vpn servers a few times and restarting the downloader i can get everything to download on the profiles i want. Sometimes i have to switch vpn servers after every model otherwise it doesn't download all content again!

**Comment by herefromrdt** [comment]
I don't know if it's related, but I've just noticed that free content for some of my subscriptions isn't being downloaded. A lot of my Free folders only have content up to mid May, even though there have been active posts since then. It only seems to affect some subscriptions. Others have recent content.

**Comment by herefromrdt** [comment]
Alright, we'll I'm not entirely sure what the problem was, but I think it might have had something to do with incompatible config file changes. I backed up my content folder, and did a hard reset of the repo folder on my computer, redid the config and auth, and now it seems to be downloading everything like usual.

**Comment by NathanIfinity** [comment]
Same issue, fresh install, only copied the .sites folder from old install, and all that gets dl is the Metadata and Profile Folder

![image](https://user-images.githubusercontent.com/75090696/126704810-e485d3a0-bfa7-4d9d-bad1-10b603f682aa.png)

**Comment by NathanIfinity** [comment]
don't know if it can help anyone, but i figured it out, in my old settings I had auto select media to "a" which was the way before, it's now changed to "0", now everything dl fine :)

**Comment by herefromrdt** [comment]
oh, good call. I'm pretty sure that's what the problem was for me, too. My backed up config file has "a", but my current working config file has "0"

**Comment by sideloading** [comment]
What does your `"filename_format":` look like? I had missing posts due to messing around with this, and not having either `{filename}` or `{media_id}` included.

**Comment by ChangeUsername** [comment]
Can confirm. Changing config.json "auto_media_choice" from "a" to "0" it works again.

@sideloading 
`"filename_format": "{filename}.{ext}",`
