### ISSUE TITLE
Failed Install (PEP 517)

### ISSUE THREAD

**Issue by yada-yoda** [DIGITALCRIMINAL/UltimaScraper#1511]
Failing to Install via cmd pip install --upgrade --user -r requirements.txt -- Reaches the wheel portion of the install and fails to build the ujson estension mentioning it requires MS Visual C++ 14.0+ (which is installed)

```
ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
```

Is this a common error with a simple fix that maybe I'm over analyzing?

**Comment by ThrowawayDane** [comment]
You are saying that you do have Visual C++ installed so you did this step to get it?
Go to visual studio downloads at https://visualstudio.microsoft.com/downloads/
Scroll down to 'All Downloads'
Click the dropdown for 'Tools for Visual Studio 2019'
Download 'Build Tools for Visual Studio 2019'
and that should successfully update wheel and allow you to install using wheels.

If you then they we will need the full error so what it say after the PEP 517 line also if you still have issuses.

Because the only thing i can find on google with this code message is because Tools for Visual Studio is missing.
