### ISSUE TITLE
does not load videos and photos

### ISSUE THREAD

**Issue by xxx-uploaded** [DIGITALCRIMINAL/UltimaScraper#1560]
downloaded a new script, there is no error, but it also does not download video and photos

![Screenshot_1](https://user-images.githubusercontent.com/88721958/128883909-319fe0ee-1ae0-4ace-97e2-05110aa6db51.png)

**Comment by ThrowawayDane** [comment]
Could it be because she have not uploaded anything new since you scraped her last.? 

Also make sure that "downloader" is set to true in config.json

You can always try and remove the Metadata folder then it will redownload everything, or allow it to  overwrite files by setting that to true in config.json

**Comment by xxx-uploaded** [comment]
> Could it be because she have not uploaded anything new since you scraped her last.?
> 
> Also make sure that "downloader" is set to true in config.json
> 
> You can always try and remove the Metadata folder then it will redownload everything, or allow it to overwrite files by setting that to true in config.json

 "downloader": true,  config all ok

deleted everything and tried to reload, unsuccessful
![Screenshot_5](https://user-images.githubusercontent.com/88721958/128890840-bf4d3bc0-8c31-4742-8008-debe8e5ac48b.png)
