### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by VeryCoolGamerMan** [DIGITALCRIMINAL/UltimaScraper#1753]
As soon as I start it I have this Issue. I updated Python, pip and sqlalchemy. I have no clue of programming and I really dont know what I'm looking at here, so any help would be appreciated.

Traceback (most recent call last):
  File "H:\OnlyFans-master\start_ofd.py", line 12, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "H:\OnlyFans-master\datascraper\main_datascraper.py", line 5, in <module>
    import helpers.main_helper as main_helper
  File "H:\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "H:\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by JaegerMedia** [comment]
Did you run pip3 install -r prerequisites prior to running start_ofd.py?

**Comment by alexey-romero** [comment]
I'm having the same issue. no changes after installing the reqs

**Comment by RazeBerry** [comment]
# Quick Guide: Solving SQLAlchemy ModuleNotFoundError with Python Virtual Environment

## Problem

You're receiving a `ModuleNotFoundError` when importing SQLAlchemy in your Python script, despite having SQLAlchemy installed in your virtual environment. This may be due to an alias overriding the Python executable in your virtual environment.

## Solution

**Step 1:** Activate your Python virtual environment.

```bash
source venv/bin/activate
```

**Step 2:** Ensure SQLAlchemy is installed in the virtual environment.

```bash
pip install sqlalchemy
```

**Step 3:** Check if `python` points to the Python in your virtual environment.

```bash
which python
```

If it points to `/usr/bin/python3` or similar, you have an alias for `python` that needs to be removed.

**Step 4:** Determine your shell (bash or zsh).

```bash
echo $SHELL
```

**Step 5:** Open your shell's configuration file (`~/.bashrc` for bash, `~/.zshrc` for zsh).

```bash
nano ~/.bashrc   # or nano ~/.zshrc
```

**Step 6:** Find the line `alias python=...` and comment it out or delete it.

**Step 7:** Save and exit (`Ctrl+X`, `Y`, `Enter` in nano).

**Step 8:** Reload your shell's configuration.

```bash
source ~/.bashrc   # or source ~/.zshrc
```

**Step 9:** Close and reopen your terminal. Activate your virtual environment again. Now `python` should point to your virtual environment's Python.

Now, try running your script. SQLAlchemy should import without error.

**Comment by Veer-w** [comment]
I tried this but still didn't worked, my python is already pointing to my virtual environment

**Comment by chouams** [comment]
I also  tried this but still didn't worked for me

**Comment by alw4ey** [comment]
I am having the same problem, and this script has worked for years until the last week. No changes to the environment (at least, none I have made.)
