### ISSUE TITLE
"Something went wrong" error when I try to log in Onlyfans

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/UltimaScraper#1917]
Hi,

**I'm having this issue since 2 or 3 days ago, it says: "Something went wrong", when it tries logging with my user:**

![image](https://user-images.githubusercontent.com/81478245/185922012-a307c624-68d4-4eae-8a6b-e4a0da7ddf53.png)

Could you help me?.

Thanks.

**Comment by silversurfer7702** [comment]
I'm getting the same thing.  I tried re-configuring my auth file with updated cookie info for OF, and get this:

![image](https://user-images.githubusercontent.com/111753340/185927608-44f89b4a-c4db-4010-be99-8a93b2080b5f.png)

So, I followed the instructions at the bottom line and downloaded the geckodriver and added it to the drive path as guided.  Then I re-configured my auth file for OF and re-ran start_ofd.  Got this:

![image](https://user-images.githubusercontent.com/111753340/185927813-8a4a1a1b-e102-404d-a854-0acbef1e06b8.png)

It seems now that whenever I run the start_ofd with a freshly configured auth file that it logs me out of OF on my browser, and then changes the OF auth file and removes my username, email, password, etc.  If anyone has any ideas, that would be great!

**Comment by FlyingSparks82** [comment]
I am also having this issue today with the exact same error code. As mentioned above, when I update my details in the auth file and run the scraper, it logs me out of OF in the browser and deletes the x-bc value from the auth file. Have OF changed something that is stopping the scraper from working?

**Comment by mbiasetti** [comment]
I'm having the same issue. This happened before almost a year ago. Something changed with the cookie info/format and I think they had to tweak something here to start sending it correctly. 

This was the original discussion: https://github.com/DIGITALCRIMINAL/OnlyFans/discussions/1791

**Comment by fightcancer2** [comment]
Same issue.

**Comment by 22none** [comment]
I believe this repo is no longer in use but the new repo had the same issue and it was solved here https://github.com/DIGITALCRIMINALS/OnlyFans/issues/595 I just followed what the comments were saying about changing the dynamic rules link and it works for me now.

**Comment by mbiasetti** [comment]
Oh awesome, good to know I'm not in the right repo. Will be giving it a
shot later. Thanks!

**Comment by fightcancer2** [comment]
> I believe this repo is no longer in use but the new repo had the same issue and it was solved here [DIGITALCRIMINALS#595](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/595) I just followed what the comments were saying about changing the dynamic rules link and it works for me now.

Thank you!

**Comment by FlyingSparks82** [comment]
Thanks for all the information, following the updates the scraper logs me in with no problem. I am now getting this error though, can anyone help me figure out what the issue is?

Type: Stories
Traceback (most recent call last):
  File "D:\Stuff\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Stuff\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Stuff\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "D:\Stuff\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\Stuff\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\Stuff\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "D:\Stuff\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "D:\Stuff\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "D:\Stuff\OnlyFans-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by mbiasetti** [comment]
Check the older discussions. I'm mobile now, but there were a few lines of
code related to stories that I had to comment out. Might be your issue.
