### ISSUE TITLE
scrape messages of people who subscribe to your profile

### ISSUE THREAD

**Issue by ghost** [DIGITALCRIMINAL/UltimaScraper#726]
Some paid accounts randomly subscribed to my account and sent videos in messages to me. I realize i could pay to subscribe to their profile, and then the script would download the videos. But I would rather not have to do that.

Is there a way to scrape these videos in messages they sent me?

**Comment by ProjektPremium** [comment]
No.

**Comment by anonCoder123** [comment]
Obviously it can't scrape their paid profile posts, but these videos in messages they sent me I'm able to watch them without subscribing. So i figured this script would be able to get those videos.

**Comment by DIGITALCRIMINAL** [comment]
> Obviously it can't scrape their paid profile posts, but these videos in messages they sent me I'm able to watch them without subscribing. So i figured this script would be able to get those videos.

I know what types of videos you're talking about. They basically spam the inbox. Theoretically, I can implement that into the scraper, but it won't be anytime soon...

**Comment by anonCoder123** [comment]
Yes usually it is spam, and I can understand why it wouldn't be implemented.

In this case it isn't spam lol, they are quality vids that were randomly sent to me.

**Comment by wobbleninja** [comment]
I'll give you an example for my case. I used to sub a Russian girl. As soon as I did my thing I stopped and she decided to sub to me so she can chat with me.

She keeps sending me stuff to buy (eve some free sexy photos that are very worth because she used to sell them for quite a bunch) and I can still make deals with her so I can get what I want and I avoid her paywall of subscription. Since she's a girl that has nothing interesting to scrape from her profile (just NN stuff), all the good content comes in messages when you do some deals with her. She kinda realized that and decided to sub to me to keep the client.

That means, I can still make deals with her (as if we're chatting somewhere else) but I can't scrape the messages because I'm not subbed to her.

**Comment by greatmate98** [comment]
i've also been longing for this feature.  I know that some girls do spam your inbox with crap.  But i have numerous who actually just keep sending out great free stuff, or great PPV previews.  But another example is a girl i keep doing deals with using an alternate payment system - i send her the cash, she sends me the content unlocked.  I can still of course get this stuff myself, but an option to scrape messages and then select who to scrape would be amazing if implemented sometime in the future,

**Comment by dunngitter** [comment]
@DIGITALCRIMINAL do you think you will work on this feature soon? I think there are at least a few people that would find it very useful
